// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/GridCommandCenter.tsx": () => import("../components/mockups/dashboard/GridCommandCenter.tsx"),
  "./components/mockups/dashboard/SectionedDashboard.tsx": () => import("../components/mockups/dashboard/SectionedDashboard.tsx"),
  "./components/mockups/dashboard/TwoColumnOps.tsx": () => import("../components/mockups/dashboard/TwoColumnOps.tsx"),
  "./components/mockups/grab-a-job/ConfirmDialog.tsx": () => import("../components/mockups/grab-a-job/ConfirmDialog.tsx"),
  "./components/mockups/grab-a-job/EmptyState.tsx": () => import("../components/mockups/grab-a-job/EmptyState.tsx"),
  "./components/mockups/grab-a-job/TaskList.tsx": () => import("../components/mockups/grab-a-job/TaskList.tsx"),
  "./components/mockups/new-task/ProgressiveForm.tsx": () => import("../components/mockups/new-task/ProgressiveForm.tsx"),
  "./components/mockups/new-task/StepperWizard.tsx": () => import("../components/mockups/new-task/StepperWizard.tsx"),
  "./components/mockups/new-task/TwoColumnForm.tsx": () => import("../components/mockups/new-task/TwoColumnForm.tsx"),
  "./components/mockups/property-detail/ContentSplit.tsx": () => import("../components/mockups/property-detail/ContentSplit.tsx"),
  "./components/mockups/property-detail/DashboardOverview.tsx": () => import("../components/mockups/property-detail/DashboardOverview.tsx"),
  "./components/mockups/property-detail/SidebarNav.tsx": () => import("../components/mockups/property-detail/SidebarNav.tsx"),
  "./components/mockups/property-list-v2/CompactPanels.tsx": () => import("../components/mockups/property-list-v2/CompactPanels.tsx"),
  "./components/mockups/property-list-v2/DashboardHub.tsx": () => import("../components/mockups/property-list-v2/DashboardHub.tsx"),
  "./components/mockups/property-list-v2/ListFirst.tsx": () => import("../components/mockups/property-list-v2/ListFirst.tsx"),
  "./components/mockups/property-list/CardGrid.tsx": () => import("../components/mockups/property-list/CardGrid.tsx"),
  "./components/mockups/property-list/CommandCenter.tsx": () => import("../components/mockups/property-list/CommandCenter.tsx"),
  "./components/mockups/property-list/SplitPanel.tsx": () => import("../components/mockups/property-list/SplitPanel.tsx"),
  "./components/mockups/property-list-v3/CommandSearch.tsx": () => import("../components/mockups/property-list-v3/CommandSearch.tsx"),
  "./components/mockups/property-list-v3/DirectoryPreview.tsx": () => import("../components/mockups/property-list-v3/DirectoryPreview.tsx"),
  "./components/mockups/property-list-v3/PriorityTimeline.tsx": () => import("../components/mockups/property-list-v3/PriorityTimeline.tsx"),
  "./components/mockups/property-list-v3/SpatialNavigator.tsx": () => import("../components/mockups/property-list-v3/SpatialNavigator.tsx"),
  "./components/mockups/property-list-v4/ListFirstRefined.tsx": () => import("../components/mockups/property-list-v4/ListFirstRefined.tsx")
};
