// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/GridCommandCenter.tsx": () => import("../components/mockups/dashboard/GridCommandCenter.tsx"),
  "./components/mockups/dashboard/SectionedDashboard.tsx": () => import("../components/mockups/dashboard/SectionedDashboard.tsx"),
  "./components/mockups/dashboard/TwoColumnOps.tsx": () => import("../components/mockups/dashboard/TwoColumnOps.tsx"),
  "./components/mockups/new-task/ProgressiveForm.tsx": () => import("../components/mockups/new-task/ProgressiveForm.tsx"),
  "./components/mockups/new-task/StepperWizard.tsx": () => import("../components/mockups/new-task/StepperWizard.tsx"),
  "./components/mockups/new-task/TwoColumnForm.tsx": () => import("../components/mockups/new-task/TwoColumnForm.tsx")
};
